name: atsign_environment_test_1
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - trunk
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github repository
        run: echo ${{ github.repository }}

      - name: Set Environment for development
        if: github.event_name == 'pull_request'
        run: echo "DEPLOY_ENV=Development" >> $GITHUB_ENV

      - name: Set Environment for Staging
        if: github.event_name == 'push' && contains(github.ref, 'trunk')
        run: echo "DEPLOY_ENV=Staging" >> $GITHUB_ENV

      - name: Set Environment for Staging
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
        run: echo "DEPLOY_ENV=Production" >> $GITHUB_ENV

  Deploy:
    name: Deployment
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.DEPLOY_ENV }}
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dart dependencies
        run: dart pub get

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install python packages
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install jproperties pyyaml argparse

      - name: Generates configuration file
        working-directory: config
        run: |
          echo root_server.url=${{ secrets.root_server_url }} >> config-environment.properties
          chmod +x generate_config.py
          python3 generate_config.py -e environment

      - name: Display variables
        run: dart lib/src/display-variables.dart